### ISSUE TITLE
Provide option for File Browser to restore last directory or revert to default directory

### ISSUE THREAD

**Issue by ThiconZ** [themeldingwars/ImTool#12]
Right now whenever the File Browser is opened and then closed, the next time it opens it will restore the last directory viewed in it. Providing an option similar to native .Net File Browser Dialogs to decide between reverting to the default directory or restoring the last directory would be beneficial.

**Comment by GoomiiV2** [comment]
You can use the optional argument on the open api for this.

``OpenFile((path) => {}, Environment.CurrentDirectory);``
