### ISSUE TITLE
Add ImTool support for ImGui.Image elements

### ISSUE THREAD

**Issue by ThiconZ** [themeldingwars/ImTool#14]
ImTool does not currently provide a way for applications to make use of ImGui.Image elements.

**Comment by freakbyte** [comment]
Added in a7d59939dd97bda9c7e3ed742510638f7bc09bf7
Look here for an example of how to use it: [Demo/DemoTool.cs](https://github.com/themeldingwars/ImTool/blob/84882f9eb6cb796c321ae0dd9798249a24758952/Demo/DemoTool.cs)
