### ISSUE TITLE
Theme WindowBorderGradientBegin/End Vector4 is ARGB instead of RGBA

### ISSUE THREAD

**Issue by ThiconZ** [themeldingwars/ImTool#15]
When configuring theme styles, all styles follow the standard RGB/RGBA formatting when defining their Vector4. However, it appears `WindowBorderGradientBegin`, `WindowBorderGradientEnd`, and `TitlebarBackgroundColor` are formatted in ARGB. This prevents using existing RGBA global color variables with these fields without modification.

It is unclear if `WindowBackgroundColor` is also ARGB formatted or not. However, given the 3 previous newly added fields are ARGB, it is likely the same as well.

**Comment by freakbyte** [comment]
Fixed in 38174b18ac1db0a4eb176bf69e71567a827d2170
All values should be RGBA now.
