### ISSUE TITLE
ImTool Window Title cannot be changed at runtime

### ISSUE THREAD

**Issue by ThiconZ** [themeldingwars/ImTool#5]
The ImTool application cannot have its window title changed at runtime due to SetWindowTitle being marked Private instead of Public.

https://github.com/themeldingwars/ImTool/blob/1048b646057f58436093e411a96ea939241dc7b5/ImTool/ImGui/ImGuiController.cs#L328

**Comment by freakbyte** [comment]
Added in f3a0c32de764706232f59f151a418a3b85f2486b
tool.Window.Title = "new title"
you can also get the original title / name from tool.Config.Title
