### ISSUE TITLE
Provide option to opt-out of ImTool User Settings file

### ISSUE THREAD

**Issue by ThiconZ** [themeldingwars/ImTool#7]
Some applications may not need to make use of User Settings. Allowing the application to compile in the various settings that would normally be stored in the ImTool User Settings configuration file (such as Application Title) would be beneficial to these situations.

**Comment by freakbyte** [comment]
Added in d745b787dd0f1fb7a061aafa9f463afc7f913890
Set DisableUserPersistence to false in the config
